# 6. 异常

在之前的示例代码中，很多时候，我们都会在发起JNI函数调用之后进行错误检查。这一节我们主要研究Native代码是如何检测错误并从错误场景中恢复的。
我们关注的错误并不是所有Native代码产生的错误，而仅仅是那些因发起JNI函数调用引起的错误。如果一个Native函数调用操作系统的API，系统会按照API文档中描述的方式去检查API调用中可能发生的错误；如果Native函数调用了一个Java函数，且在这个函数的执行过程中发生了错误，那它就必须按照本节描述的步骤做适当的检查并从可能的异常中恢复回来。

# 6.1 概览

以下我们用一系列的示例带密码来介绍JNI的异常处理功能。

# 6.1.1 在Native代码中捕获与抛出异常

以下的代码中展示了如何声明一个抛出异常的Native函数。`CatchThrow`类声明了`doit`这个Native函数，并且指定了它将有可能抛出一个`IllegalArgumentException`.

```
public class CatchThrow {
  static {
    System.loadLibrary("CatchThrow");
  }
  private native void doit() throws IllegalArgumentException;
  private void callback() throws NullPointerException {
    throw new NullPointerException("CatchThrow.callback");
  }
  public static void main(String[] args){
    CatchThrow c = new CatchThrow();
    try {
      c.doit();
    }catch (Exception e){
      System.out.println("In Java:\n\t" + e);
    }
  }
}
```

CatchThrow.main函数调用的Native方法doit的JNI实现如下：

```
/*
 * Class:     CatchThrow
 * Method:    doit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CatchThrow_doit
  (JNIEnv * env, jobject obj){
  jthrowable exc;
  jclass cls = (*env)->GetObjectClass(env, obj);
  jmethodID mid = (*env)->GetMethodID(env, cls, "callback", "()V");
  if(!mid){
    return;
  }
  (*env)->CallVoidMethod(env, obj, mid);
  exc = (*env)->ExceptionOccurred(env);
  if(exc){
      /*
       * We don't do much with the exception, except that we print a debug message for it,
       * clear it, and throw a new exception.
       */
      jclass newExcCls;
      (*env)->ExceptionDescribe(env);
      (*env)->ExceptionClear(env);
      newExcCls = (*env)->FindClass(env, "java/lang/IllegalArgumentException");
      if(!newExcCls){
        /*Unable to find the exception class, give up. */
        return;
      }
      (*env)->ThrowNew(env, newExcCls, "thrown from C code");
  }
}
```

执行最终的可执行程序将会产生如下输出：

```
Exception in thread "main" java.lang.NullPointerException: CatchThrow.callback
	at CatchThrow.callback(CatchThrow.java:7)
	at CatchThrow.doit(Native Method)
	at CatchThrow.main(CatchThrow.java:12)
In Java:
	java.lang.IllegalArgumentException: thrown from C code
```

回调函数跑出了一个NullPointerException.当CallVoidMethod返回到Native函数时，Native代码通过ExceptionOccurred函数检测到这个异常。在我们的示例中，当异常被检测到的时候， Native代码通过调用ExceptionDescribe输出了一段描述性信息，然后调用ExceptionClear清除了异常信息，最后抛出了一个IllegalArgumentException.

JNI代码引起的异常（例如，通过ThrowNew抛出的异常）不会立即打断Native代码的执行流程。这与Java程序语言中异常处理逻辑是不同的。在Java语言中，如果有异常被抛出，虚拟机就会自动的把控制流程转向匹配异常类型的最近层次的try/catch语句声明，然后虚拟机清空异常并继续执行异常处理逻辑。相比之下，JNI程序员在异常出现的时候必须显示实现代码的控制流程。

# 6.1.2 工具函数

抛出一个异常包括两个步骤：

1. 照抄异常对应的类型
2. 调用ThrowNew函数。
   为了简化这个任务，我们通常会写一个工具函数用来抛出一个指定名字的异常。

```
void JNU_ThrowByName(JNIEnv *env, const char* name, const char* msg){
  jclass cls = (*env)->FindClass(env, name);
  /*if cls is NULL, an exception has already been thrown */
  if(cls){
    (*env)->ThrowNew(env, cls, msg);
  }
  /* free the local ref */
  (*env)->DeleteLocalRef(env, cls);
}
```

在本书中,"JNU" 前缀表示JNI Utilities. JNU_ThrowByName 首先调用FindClass查找到异常对应的类型，如果累查找失败（return NULL), 虚拟机必须抛出一个异常（比如NoClassDefFoundError).在这个示例中，JNU_ThrowByName没有尝试抛出其他的异常。如果FindClass成功，我们会调用ThrowNew抛出指定名字的异常，当JNI_ThrowNew返回的时候，它会保证有一个异常正在抛出，尽管这个异常不必与指定的异常名称相匹配，我们需要保证删除指向在这个函数调用中创建的异常的本地引用。如果传递NULL给DeleteLocalRef，什么都不会执行，所以对于FindClass失败并返回NULL的时候调用这个函数处理返回值，也是可以的。

# 6.2 异常处理最佳实践

JNI程序员必须预见代码中可能发生的异常并编写检查和处理异常的代码。适当的异常处理代码虽然会让代码变得有点冗长，但是为了让我们的应用程序更加健壮这也是值得的。

# 6.2.1 异常检查

有两种方式可以检测JNI代码中是否有错误发生。

1. 大多数JNI函数使用一个不同的返回值（比如NULL)来标识有错误发生。这个错误返回值也暗示着在当前线程有一个异常。
   以下代码展示了如何使用NULL对比返回值的方式检查GetFieldID是否发生错误。这个示例包括两部分：一个类Window定义了一些属性（handle, length以及width)以及一个Native方法用于缓存这些属性的ID。尽管这些属性在Window类中是存在的，我们仍然需要检查从GetFieldID函数返回的可能的错误，因为虚拟机可能不能为属性ID分配足够的内存空间。

```
public class Window{
  static {
    initIDs();
  }
  long handle;
  int length;
  int width;
  static native void initIDs();
}
/*
 * Class:     Window
 * Method:    initIDs
 * Signature: ()V
 */
jfieldID FID_Window_handle;
jfieldID FID_Window_length;
jfieldID FID_Window_width;
JNIEXPORT void JNICALL Java_Window_initIDs
  (JNIEnv * env, jclass classWindow){
  FID_Window_handle = (*env)->GetFieldID(env, classWindow, "handle", "J");
  if(!FID_Window_handle){
      return; /* error occured ! */
  }
  FID_Window_length = (*env)->GetFieldID(env, classWindow, "length", "I");
  if(!FID_Window_length){
      return; /* error occured ! */
  }
  FID_Window_width= (*env)->GetFieldID(env, classWindow, "width", "I");
  if(!FID_Window_width){
      return; /* error occured ! */
  }
  
 /* no check necessary; we are about to return anyway */
}
```

1. 当使用一个返回值不能标识其内部是否有错误发生的JNI函数时，Native代码必须依赖异常检查来检查是否有错误发生。检查当前函数是否有异常发生的JNI函数是ExceptionOccurred.(ExceptionCheck 在Java 2 SDK relaease 1.2)也被加进来了。例如，JNI函数CallIntMethod不能将错误场景都编码到返回值中，像-1或者NULL这样的通常的错误场景返回值此时并不能作为判断是否有错误产生的依据了，因为它们可能是被调用函数的合法返回值。想一下，有一个Fraction（小数）类，它的floor方法返回小数值的整数部分，另一个JNI函数调用了它。

```
public class Fraction {
  // details such as constructors omitted
  int over, under;
  public int floor() {
    return Math.floor((double)over/under);
  }
}
/* Native code that calls Fraction.floor. Assume method ID MID_Fraction_floor has been initialized elsewhere. */
void f(JNIEnv *env, jobject fraction) {
  jint floor = (*env)->CallIntMethod(env,fraction, MID_Fraction_floor);
  /* important: check if an exception was raised */
  if((*env)->ExceptionCheck(env)) {
    return;
  }
  /*...use floor */
}
```

当JNI函数返回了一个明确的错误码，Native代码仍然可以使用像ExceptionCheck这样的函数检查是否有异常发生。不过显然，通过返回值检查异常往往会更高效。如果一个JNI函数返回了它的错误代码，在当前线程如果紧接着调用的ExceptionCheck，其返回值将保证返回JNI_TRUE.

# 6.2.2 异常处理

Native代码有两种方式处理发生的异常：

- Native方法的实现可以选择立即返回，或者让Native方法的调用者处理异常。
- Native代码可以直接调用ExceptionClear清除当前异常并自己处理（这样Native的调用者就不必处理异常了）。
  切记，在发起后续JNI调用之前，需要检查，处理并清除异常。如果发起一个JNI调用的时候已经发生了一个异常且这个异常没有被清除，除了少数函数（见11.8.2）可以被安全的调用 则该JNI调用的结果是未知的。这少数函数基本上都是JNI本来设计用来处理异常的以及用来释放虚拟机资源的函数。
  通常在发生异常的时候我们有必要释放异常发生之前申请的资源。在以下示例中，Native函数首先调用GetStringChars获取一个字符串，然后在后续操作失败之后调用ReleaseStringChars释放字符串资源：

```
JNIEXPORT void JNICALL Java_pkg_Cls_f(JNIEnv *env, jclass cls, jstring jstr) {
  const jchar *cstr = (*env)->GetStringChars(env, jstr);
  if(!cstr){
    return;
  }
  if(...) { /*exception occurred */
    (*env)->ReleaseStringChars(env, jstr, cstr);
    return;
  }
  /* normal return */
  (*env)->ReleaseStringChars(env, jstr, cstr);
}
```

第一个ReleaseStringChars是在发生异常的时候被调用的。在这里我们只是在发生异常之后释放了相关的资源然后立即返回，而并没有清除异常。

# 6.2.3 工具函数中的异常

在编写工具函数时候应当注意把工具函数中可能发生的异常通过某种方式暴露给调用者，使他们能够处理这些异常。特别是在以下两种场景下：

- 工具函数最好提供一个特殊的返回值来标识函数中发生的异常，可以让调用者方便的检查异常。
- 另外，工具函数在发生异常的时候，应当按照5.3节描述的规则来管理局部引用。
  让我们通过一个例子来更清楚的了解这两种状况，以下是一个工具函数，通过一个对象示例方法描述符和名字属性调用一个Java函数：

```
jvalue JNU_CallMethodByName(JNIEnv *env, jboolean * hasException, jobject obj, const char * name, const char*descriptor, ...){
    va_list args;
    jclass clazz;
    jmethodID mid;
    jvalue result;
    if((*env)->EnsureLocalCapacity(env, 2) == JNI_OK) {
      clazz = (*env)->GetObjectClass(env, obj);
      mid = (*env)->GetMethodID(env, clazz, name, descriptor);
      if(mid){
        const char *p = descriptor;
        /*skip over argument types to find out the return type */
        while(*p != ')') p++;
        /* skip ')' */
        p ++;
        va_start(args, descriptor);
        switch(*p){
          case 'V':
              (*env)->CallVoidMethod(env, obj, mid, args);
              break;
          case '[':
          case 'L':
              result.l = (*env)->CallObjectMethodV(env, obj, mid, args);
              break;
          case 'Z':
              result.z = (*env)->CallBooleanMethodV(env, obj, mid, args);
              break;
          case 'B':
              result.b = (*env)->CallByteMethodV(env, obj, mid, args);
              break;
          case 'C':
              result.c = (*env)->CallCharMethodV(env, obj, mid, args);
              break;
          case 'S':
              result.s = (*env)->CallShortMethodV(env, obj, mid, args);
              break;
          case 'I':
              result.i = (*env)->CallIntMethodV(env, obj, mid, args);
              break;
          case 'J':
              result.j = (*env)->CallLongMethodV(env, obj, mid, args);
              break;
          case 'F':
              result.f = (*env)->CallFloatMethodV(env, obj, mid, args);
              break;
          case 'D':
              result.d = (*env)->CallDoubleMethodV(env, obj, mid, args);
              break;
          default:
              (*env)->FatalError(env, "illegal descriptor");
        }
        va_end(args);
      }
      (*env)->DeleteLocalRef(env, clazz);
    }
    if(hasException){
      *hasException = (*env)->ExceptionCheck(env);
    }
    return result;
}
```

JNU_CallMethodByName使用了一个额外的jboolean类型的参数hasException用于保存函数执行过程是否出现异常的标志位，如果所有操作都成功，则被设置为JNI_FALSE, 否则被设置为JNI_TRUE.
JNU_CallMethodByName首先检查了是能够创建两个局部引用：一个为了保存类引用，另一个则为了保存函数调用的返回值。然后，获取对象对应的类并查找函数对应的函数ID。接下来在switch处理流程中根据返回值类型调用不同的JNI函数。最后，如果hasException不为空，则调用ExceptionCheck检查异常并将值赋值给hasException.
ExceptionCheck函数是在Java 2 SDK release 1.2中加入的，它与ExceptionOccurred函数的作用类似，不同之处在于ExceptionCheck函数不会返回异常对象的引用，而是返回一个异常是否发生的jboolean标识.所以，当调用者不关心异常的类型，仅仅关心是否发生了异常的时候，使用它会很方便而且高效。上边异常检查的代码如果用ExceptionOccurred重写如下：

```
if(hasException) {
  jthrowable exc = (*env)->ExceptionOccurred(env);
  *hasException = exc != NULL;
  (*env)->DeleteLocalRef(env, exc);
}
```

如上代码，需要额外的调用DeleteLocalRef来删除指向异常对象的引用。
使用JNU_CallMethodByName函数，我们可以重写4.2节的InstanceMethodCall.nativeMethod如下：

```
JNIEXPORT void JNICALL Java_InstanceMethodCall_nativeMethod(JNIEnv *env, jobject obj){
  printf("In C\n");
  JUN_CallMethodByName(env, NULL, obj, "callback", "()V");
}
```

我们不需要再JNU_CallMethodByName调用之后检查异常因为这个函数会在调用JNU_CallMethodByName之后立刻返回。